# MediConnect API - Configuración General
spring.application.name=MediConnect API
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.dev.mxd.mediconnect=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Jackson - Serialización JSON
spring.jackson.default-property-inclusion=non_null
spring.jackson.time-zone=UTC

# Mensajes de Negocio
mediconnect.doctor.not.found=Doctor no encontrado
mediconnect.appointment.not.found=Cita no encontrada
mediconnect.invalid.specialty=Especialidad inválida
mediconnect.duplicate.license=Tarjeta profesional duplicada
mediconnect.schedule.conflict=Conflicto en la agenda del doctor
mediconnect.patient.forbidden=Acceso denegado para el paciente
mediconnect.appointment.cancelled=Cita cancelada exitosamente

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
