spring.datasource.url=jdbc:h2:mem:mediconnect_db
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.data.mongodb.uri=mongodb://localhost:27017/mediconnect_dev
logging.level.com.dev.mxd.mediconnect=DEBUG